spring:
  application:
    name: lion-apple
  datasource:
    url: jdbc:mysql://localhost:3306/lion_apple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Qkrgoehf0206@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

google:
  oauth:
    client-id: 964129047813-hdnng4fd73r6cmvt5mid5u6ime9d6l39.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET:}
